@startuml
Package "Model" {
    class MapController {
        addBuilding(position)
    }
    class MapGenerator {
        size
        generate()
    }
    class Building {
        constructionGameTime
        constructionStartedAt
        isUnderConstruction
        calculateSatisfaction()
    }
    class DecorationObject {
        calculateSatisfaction()
    }
    class LeisureBuilding {

        calculateSatisfaction()
    }
    class AccommodationBuilding {
        rentPrice
        commonRooms
        calculateSatisfaction()
    }
    class TeachingBuilding {
        lectureHallCount
        labCount
        classroomCount

        calculateSatisfaction()
    }
    class Cafeteria {
        foodQuality
        hygieneRating
        calculateSatisfaction()
    }
    abstract class MapObject {
        name
        sprite
        shape
        capacity
        isStackable
        calculateSatisfaction()
    }
    class EventManager {
        eventChancePerSec
        processEvents()
    }
    class GameEvent {
        title
        description
        rarity
        iconPath
        modifiers
    }
    class ScoreCalculator {
        activeModifiers
        currentScore
        currentStudents
    }
    class Timer {
        timeSeconds
        tick()
    }
    class GameModel {
        gameState
    }
    class AudioSelector {
        tracks
        selectTrack()
    }
}
Package "View" {
    class MainScreen {
        create()
        render()
    }
    class UILogic {
        generatePauseScreen()
        generateMainScreen()
        generateEndScreen()
    }
}
Package "Controller" {
    class PlayerInputHandler {
        PAUSE_KEY
        isMouseDown
        isPausePressed
        mousePos
        handleInput()
    }
}

Building ..|> MapObject
DecorationObject ..|> MapObject
LeisureBuilding --|> Building
AccommodationBuilding --|> Building
TeachingBuilding --|> Building
Cafeteria --|> Building

MapController -- MapGenerator
MapController -- MapObject

MainScreen -- GameModel

PlayerInputHandler -- GameModel
PlayerInputHandler -- MainScreen

UILogic -- MainScreen

GameModel -- Timer
GameModel -- ScoreCalculator
GameModel -- EventManager
GameModel -- MapController
GameModel -- AudioSelector

EventManager -- GameEvent

@enduml
